[pytest]
asyncio_mode = auto
testpaths = tests
addopts =
    --cov=.
    --cov-report=term-missing
    --cov-report=html:htmlcov
filterwarnings =
    ignore::DeprecationWarning

[coverage:run]
omit =
    alembic/*
    tests/*
    htmlcov/*